"""create tables

Revision ID: e26a498df410
Revises: 
Create Date: 2025-08-30 15:41:21.700395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26a498df410'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('items', 'location_id',
               #existing_type=sa.INTEGER(),
               #nullable=False)
    #op.alter_column('items', 'user_id',
              # existing_type=sa.INTEGER(),
              # nullable=False)
    op.create_unique_constraint(None, 'locations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    op.alter_column('items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
